/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_eddiep_lifxbulb_rave_system_WASAPI */

#ifndef _Included_me_eddiep_lifxbulb_rave_system_WASAPI
#define _Included_me_eddiep_lifxbulb_rave_system_WASAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_eddiep_lifxbulb_rave_system_WASAPI
 * Method:    loadWrapper
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_me_eddiep_lifxbulb_rave_system_WASAPI_loadWrapper
  (JNIEnv *, jobject);

/*
 * Class:     me_eddiep_lifxbulb_rave_system_WASAPI
 * Method:    getSoundData
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_me_eddiep_lifxbulb_rave_system_WASAPI_getSoundData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
